# Generated by Django 3.0.3 on 2020-07-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
